- name: "Update package cache"
  dnf:
    update_cache: yes

- name: "Install nginx"
  dnf:
    name: nginx
    state: present

- name: "Setup virtual hosts folder"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled
