# For more secure MySQL installation & hardening, you can refer to this repository
# https://github.com/dev-sec/ansible-collection-hardening

- name: Install MySQL 5.7
  become: true
  import_tasks: install-57.yml
  when: mysql_version == '5.7' and ansible_os_family == 'Debian'

- name: Install MySQL 8.0
  become: true
  import_tasks: install-80.yml
  when: mysql_version == '8.0' and ansible_os_family == 'Debian'

- name: Install necessary mysql packages
  when: ansible_os_family == 'Debian'
  apt:
    pkg:
      - gnupg2
      - python3-mysqldb

- name: Ensure MySQL is enabled to run on startup  
  service: name=mysql state=started enabled=true

- name: Update MySQL root password
  mysql_user:
    name: "{{ mysql_root_username }}"
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:  
  - 127.0.0.1
  - ::1
  - localhost

- name: Copy root-my.cnf file with password credentials.
  template:
    src: "root-my.cnf.j2"
    dest: "{{ mysql_root_home }}/.my.cnf"
    owner: "{{ mysql_root_username }}"
    mode: 0600

- name: Deletes anonymous MySQL server user for ansible_fqdn
  mysql_user:
    user: ""
    host: "{{ ansible_fqdn }}"
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    state: "absent"

- name: Deletes anonymous MySQL server user for localhost
  mysql_user:
    user: ""
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    state: "absent"

- name: Disallow root login remotely
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='{{ mysql_root_username }}' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

- name: Remove MySQL test database.
  mysql_db:
    name: 'test'
    state: absent

- name: Get list of hosts for the anonymous user.
  become: true
  command: mysql -NBe "SELECT Host FROM mysql.user WHERE User = ''"
  register: mysql_anonymous_hosts
  changed_when: false
  check_mode: false

- name: Remove anonymous MySQL users.
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items: "{{ mysql_anonymous_hosts.stdout_lines|default([]) }}"

- name: Cleanup root-my.cnf file with password credentials
  file:
    path: "{{ mysql_root_home }}/.my.cnf"
    state: absent