- name: Setup PHP on RedHat Family
  become: true
  import_tasks: setup-redhat.yml
  when: ansible_os_family in ["RedHat", "Rocky"]

- name: Setup PHP on Debian Family
  become: true
  import_tasks: setup-debian.yml
  when: ansible_os_family == "Debian"