- block: ########################################## RedHat Family
  - name: Adding Remi repo pgp keys
    when: ansible_os_family in ["RedHat", "Rocky"]
    get_url:
      url: "{{ remi_repo_gpg_key_url }}"
      dest: "{{ remi_repo_gpg_file }}"

  - name: Add remi repo
    when: ansible_os_family in ["RedHat", "Rocky"]
    yum_repository: 
      name: remi
      description: Remi repo for Enterprise Linux 9
      mirrorlist: "{{ remi_repo_mirrorlist }}"
      enabled: true
      gpgcheck: true
      repo_gpgcheck: true
      gpgkey: file:///{{ remi_repo_gpg_file }}

  - name: Add remi-modular repo
    when: ansible_os_family in ["RedHat", "Rocky"]
    yum_repository:
      name: remi-modular
      description: Remi's Modular repository for Enterprise Linux {{ ansible_distribution_major_version }}
      mirrorlist: "{{ remi_repo_mirrorlist }}"
      enabled: true
      gpgcheck: true
      repo_gpgcheck: true
      gpgkey: file:///{{ remi_repo_gpg_file }}

  - name: Adding remi-safe repo
    when: ansible_os_family in ["RedHat", "Rocky"]
    yum_repository:
      name: remi-safe 
      description: Remi's RPM repository for Enterprise Linux {{ ansible_distribution_major_version }}
      mirrorlist: "{{ remi_repo_mirrorlist }}"
      enabled: true
      gpgcheck: true
      repo_gpgcheck: true
      gpgkey: file:///{{ remi_repo_gpg_file }}

  - name: "Enable PHP {{ php_version }} remi repo"
    when: ansible_os_family in ["RedHat", "Rocky"]
    shell: dnf module enable php:remi-{{ php_version }} -y

  - name: "Install PHP {{ php_version }} [ RedHat Family ]"
    when: ansible_os_family in ["RedHat", "Rocky"]
    dnf:
      state: present
      name:
        - php-cli
        - php-fpm
        - php-pdo
        - php-json
        - php-mysqlnd
        - php-intl
        - php-soap
        - php-mbstring
        - php-curl
        - php-xml
        - php-bcmath
        - php-xmlrpc
        - php-gd
        - php-zip
        - php-sodium



  # - name: Installing PHP {{ php_version }} on [RedHat Family]
  #   when: ansible_os_family in ["RedHat", "Rocky"]
  #   state: present
  #   dnf:
  #     name:
  # - name: Import remi GPG key
  #   when: ansible_os_family in ["RedHat", "Rocky"]
  #   rpm_key:
  #     key: "{{ remi_repo_gpg_key_url }}"
  #     state: present

  # - name: Install remi repo
  #   when: ansible_os_family in ["RedHat", "Rocky"]
  #   yum:
  #     name: "{{ remi_repo_url }}"
  #     state: present

  # - name: Install php{{ php_version | replace('.','') }} [ RedHat Family ]
  #   when: ansible_os_family == "RedHat"
  #   yum: 
  #       name:
  #         - php{{ php_version | replace('.','') }}
  #         - php{{ php_version | replace('.','') }}-php-mcrypt
  #         - php{{ php_version | replace('.','') }}-php-mbstring
  #         - php{{ php_version | replace('.','') }}-php-fpm
  #         - php{{ php_version | replace('.','') }}-php-gd
  #         - php{{ php_version | replace('.','') }}-php-xml
  #         - php{{ php_version | replace('.','') }}-php-pdo
  #         - php{{ php_version | replace('.','') }}-php-zip 
  #       enablerepo: "remi" 
  #       state: present
    # - name: Change php.ini [ CentOS ] 
    #   template:
    #     src: php.ini
    #     dest: /etc/opt/remi/php{{ php_ver | replace('.','') }}/php.ini
    #   become: yes
    # - name: Change php-fpm pool [ CentOS ] 
    #   template:
    #     src: www.conf
    #     dest: /etc/opt/remi/php{{ php_ver | replace('.','') }}/php-fpm.d/www.conf
    #   become: yes
    # - name: Ensure php{{ php_ver | replace('.','') }}-php-fpm is running [ CentOS ]
    #   service: name=php{{ php_ver | replace('.','') }}-php-fpm state=started enabled=yes
    #   notify:
    #     - restart php-fpm CentOS
    #   when: ansible_distribution == "CentOS"   

- block: ########################################## Debian Family
  - name: "Add Repository for PHP {{ php_version }}"
    when: ansible_os_family == "Debian"
    apt_repository:
      repo: "ppa:ondrej/php"
      update_cache: true

  - name: "Install PHP {{ php_version }}"
    when: ansible_os_family == "Debian"
    apt:
      state: present
      pkg:
        - php{{ php_version }}

  - name: Install PHP packages & extensions
    when: ansible_os_family == "Debian"
    apt:
      state: present
      install_recommends: no
      pkg:
        - openssl
        - php{{ php_version }}-mysql
        - php{{ php_version }}-bcmath
        - php{{ php_version }}-common
        - php{{ php_version }}-bz2
        - php{{ php_version }}-curl
        - php{{ php_version }}-redis
        - php{{ php_version }}-fpm
        - php{{ php_version }}-gd
        - php{{ php_version }}-mbstring
        - php{{ php_version }}-zip
        - php{{ php_version }}-xmlrpc
        - php{{ php_version }}-intl
        - php{{ php_version }}-sqlite3
        - php{{ php_version }}-xml
        - php{{ php_version }}-tokenizer 

  - name: Change php-fpm pool
    when: ansible_os_family == "Debian"
    template:
      src: www.conf.j2
      dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
    become: true
    notify:
      - Restart PHP-FPM
