- name: "Add Repository for PHP {{ php_version }}"
  apt_repository:
    repo: "ppa:ondrej/php"
    update_cache: true

- name: "Install PHP {{ php_version }}"
  apt:
    state: present
    pkg:
      - php{{ php_version }}

- name: Install PHP packages & extensions
  apt:
    state: present
    install_recommends: no
    pkg:
      - openssl
      - php{{ php_version }}-mysql
      - php{{ php_version }}-bcmath
      - php{{ php_version }}-common
      - php{{ php_version }}-bz2
      - php{{ php_version }}-curl
      - php{{ php_version }}-redis
      - php{{ php_version }}-fpm
      - php{{ php_version }}-gd
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-zip
      - php{{ php_version }}-xmlrpc
      - php{{ php_version }}-intl
      - php{{ php_version }}-sqlite3
      - php{{ php_version }}-xml
      - php{{ php_version }}-tokenizer 

- name: Change php-fpm pool
  template:
    src: www.conf.j2
    dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
  become: true
  notify:
    - Restart PHP-FPM